# Generated by Django 4.0.4 on 2022-05-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='numero_turno',
            field=models.IntegerField(unique=True),
        ),
    ]
